<?php

/**
 * User
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    myproject
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class User extends BaseUser
{
    // DB保存する際にcreated_atに日付を自動的に入れるために用意
    public function preSave($event)
    {
        if ($this->isNew() && !$this->getCreatedAt()) {
            $this->setCreatedAt(date('Y-m-d H:i:s'));
        }

        // 更新時に updated_at を設定
        $this->setUpdatedAt(date('Y-m-d H:i:s'));

        parent::preSave($event);
    }
}