<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2025/09/18 21:27:40

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=myproject',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
